import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';


const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: 'Next.js Press Frontend',
    description: 'Generated by nextjs-press-frontend',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
        >
            <body className="min-h-full flex flex-col">
                <Toaster position="top-right" richColors />
                {children}
                {/* {Footer} */}
            </body>
        </html>
    );
}
